AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-kanban

  Sample SAM Template for sam-kanban
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Handler: app.handler
    Runtime: nodejs12.x
    Layers: 
      - !Ref XRayLayer

Resources:
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: kanban-api
      StageName: dev
      TracingEnabled: true

  XRayLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs12.x
      ContentUri: layers/xraysdk
      LayerName: aws-xray-sdk
      Description: aws-xray-sdk layer
      RetentionPolicy: Retain

  GetCardsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/getCards
      Role: arn:aws:iam::000140339722:role/Lambda-Kanban-Role
      FunctionName: kanban-getCards
      Description: kanban-getCards lambda
      Events:
        Trigger:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /kanban/cards
            Method: get
            Auth:
              ApiKeyRequired: true
            RestApiId: !Ref APIGateway

  DynamoDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: Cards

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  APIGateway:
    Description: "API Gateway endpoint URL for Prod stage for Kanban project"
    Value: !Sub "https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/dev"
